name: Lint Markdown (Remark)

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install remark-lint
        npm install remark-cli remark-preset-lint-markdown-style-guide
        npm run lint-md
      #if: github.ref == 'refs/heads/master' && github.repository == 'larshp/abapOpenChecks'
      #npm install remark-cli remark-preset-lint-recommended